# Generated by Django 3.2.4 on 2022-03-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_address', '0001_initial'),
        ('orders', '0002_auto_20220317_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping_address.shippingaddress'),
        ),
    ]
